CREATE TABLE [dbo].[events]
(
[Code (CALC)] varchar(100),
[Code] varchar(100),
[Property] varchar(100),
[Event space] varchar(100),
[Region] varchar(100),
[REMOVE] varchar(100),
[Show kitchen or built in induction to feature live cooking displays ] varchar(100),
[Full service bars for prefunction area ] varchar(100),
[Meeting or event room is  equipped to offer a  High quality barista experience ] varchar(100),
[Meeting or event room has concealable beverage and barista bars ] varchar(100),
[Meeting or event room offers exterior Views ] varchar(100),
[SCORE (Incorp. Of Design)] varchar(100),
[Outdoor event space is currently  available for events ] varchar(100),
[Creating Outdoor space could be part of future renovation plan ] varchar(100),
["Outdoor event space is  equipped with kitchens bars or adequate power supply.  "] varchar(100),
[SCORE (Outdoor space)] varchar(100),
["FS Approved Design (1=Yes 0=No)"] varchar(100),
["Project Executed as FS-Approved (incl. appd Art & Accessories Pkg) 0.5=Fully 0.5=Partially 0=No"] varchar(100),
[SCORE (QoD)] varchar(100),
["Medallia (out of 100)"] varchar(100),
["Age of Product (<7yrs=2 7-10yrs=1 >10yrs = 0) (CALCULATED)"] varchar(100),
[Date of Last Reno (MM-YY)] varchar(100),
[Do you have a long life projector with 1080p resolution as approved by the AV Consultant?] varchar(100),
[Do you have a commercial quality audio system that is from a recognized brand and approved by the AV consultant?] varchar(100),
[Do you have widely available high speed internet access throughout your meeting and event spaces?] varchar(100),
[Do you have an extensive lighting infrastructure approved by the lighting consultant?] varchar(100),
[Do you have widely available charging facilities for patrons to charge mobile devices?] varchar(100),
[SCORE (Tech)] varchar(100),
[Sqft] varchar(100),
[Comments] varchar(100)
);