CREATE TABLE [dbo].[fandb]
(
[Code (CALC)] varchar(100),
[Code] varchar(100),
[Property] varchar(100),
[Event space] varchar(100),
[Region] varchar(100),
[Category] varchar(100),
[REMOVE] varchar(100),
[Clear and Individual Concept] varchar(100),
[Environment that Fosters Connections ] varchar(100),
[Local Community ] varchar(100),
[Food and Drink Craftmanship ] varchar(100),
["Fulfillment of Role: Bar Lounge and Restaurants have unique roles to play "] varchar(100),
["Score (Connection) (Calculated)"] varchar(100),
["FS Approved (1=Yes 0=No)"] varchar(100),
["Project Executed as FS App'd (incl. app'd Art & Accessories Pkg) 1=Fully 0.5=Partially 0=No"] varchar(100),
[Score (QoD) (Calculated)] varchar(100),
["Medallia (out of 100)"] varchar(100),
["Age of Product (<7yrs=2 7-10yrs=1 >10yrs = 0) (CALCULATED)"] varchar(100),
[Date of Last Reno (MM-YY)] varchar(100),
[Revenue Contribution] varchar(100),
[Comments] varchar(100),
);