CREATE TABLE [dbo].[suites]
(
[#] varchar(100),
[Code] varchar(100),
[Property (Calculated)] varchar(100),
[Region (Calculated)] varchar(100),
[Sense of Place] varchar(100),
[Personality / Character] varchar(100),
[Layering / Richness] varchar(100),
[Residential Style] varchar(100),
[SCORE (Calculated)] varchar(100),
[Quality of Execution SCORE] varchar(100),
["Medallia (out of 100) (Calculated)"] varchar(100),
[Televisions] varchar(100),
[Telephone] varchar(100),
[Audio] varchar(100),
[SCORE2 (Calculated)] varchar(100),
[Tabletop - MyBar] varchar(100),
[Bathroom setup] varchar(100),
[The Bundle Compliance] varchar(100),
[SCORE3 (Calculated)] varchar(100),
["Age of Product (<7yrs=2 7-10yrs=1 >10yrs = 0) (CALCULATED)"] varchar(100),
[Date of Last Reno (MM-YY)] varchar(100),
[Comments] varchar(100)
);